// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUPr0Cg5MrGOmppMH4wgDf99c-q994uI',
    appId: '1:765090368484:web:421c0de8d6121233b3d5f1',
    messagingSenderId: '765090368484',
    projectId: 'ecommerceapp-ce6fb',
    authDomain: 'ecommerceapp-ce6fb.firebaseapp.com',
    storageBucket: 'ecommerceapp-ce6fb.appspot.com',
    measurementId: 'G-6PL9339T4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdiVDLJU8z4f6lhmc33kNTd_AfXZ3PL0',
    appId: '1:765090368484:android:15fec5f2edb25636b3d5f1',
    messagingSenderId: '765090368484',
    projectId: 'ecommerceapp-ce6fb',
    storageBucket: 'ecommerceapp-ce6fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZkqO3H5T4htNbWSmzbfWqVTxxPBUyqWM',
    appId: '1:765090368484:ios:3190de231ff209ffb3d5f1',
    messagingSenderId: '765090368484',
    projectId: 'ecommerceapp-ce6fb',
    storageBucket: 'ecommerceapp-ce6fb.appspot.com',
    iosBundleId: 'com.example.webapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZkqO3H5T4htNbWSmzbfWqVTxxPBUyqWM',
    appId: '1:765090368484:ios:efc232724fe5577fb3d5f1',
    messagingSenderId: '765090368484',
    projectId: 'ecommerceapp-ce6fb',
    storageBucket: 'ecommerceapp-ce6fb.appspot.com',
    iosBundleId: 'com.example.webapplication.RunnerTests',
  );
}
